"""
Robot script generation for ABB robots and G-code for CNC plasma cutters.
"""

from typing import List, Tuple


class RobotScriptGenerator:
    """Generate robot scripts from vector paths."""

    @staticmethod
    def generate_abb_script(
        paths: List[List[Tuple[float, float]]],
        z_height: float,
        speed_mm_s: float,
        scale_mm_per_px: float,
        origin_x: float,
        origin_y: float
    ) -> str:
        """
        Generate ABB robot script.

        Args:
            paths: List of paths in robot coordinates (mm)
            z_height: Z height in mm
            speed_mm_s: Movement speed in mm/s
            scale_mm_per_px: Scale used for coordinate transformation
            origin_x: Origin X offset
            origin_y: Origin Y offset

        Returns:
            ABB robot script as string
        """
        lines = []
        lines.append("! Robot welding script generated from AI path detection")
        lines.append(f"! Generated by AI Welding Path Generator - IronSketch")
        lines.append(f"! Scale: {scale_mm_per_px} mm/px")
        lines.append(f"! Origin offset: X={origin_x:.1f} mm, Y={origin_y:.1f} mm")
        lines.append(f"! Z height: {z_height:.1f} mm")
        lines.append(f"! Speed: {speed_mm_s:.1f} mm/s")
        lines.append("")

        for path_idx, path in enumerate(paths, 1):
            lines.append(f"! Path {path_idx} ({len(path)} points)")

            for point_idx, (x_mm, y_mm) in enumerate(path):
                speed_var = f"v{int(speed_mm_s)}"

                line = (
                    f"MoveL [[{x_mm:.1f},{y_mm:.1f},{z_height:.1f}],"
                    f"[0,0,1,0]], {speed_var}, z10, tool0\\WObj:=wobj0;"
                )
                lines.append(line)

            lines.append("")

        lines.append(f"! Total paths: {len(paths)}")
        lines.append(f"! Total points: {sum(len(p) for p in paths)}")

        return "\n".join(lines)

    @staticmethod
    def generate_gcode(
        paths: List[List[Tuple[float, float]]],
        z_height: float,
        feed_rate: float,
        z_clearance: float = 10.0
    ) -> str:
        """
        Generate G-code for CNC plasma cutter.

        Args:
            paths: List of paths in robot coordinates (mm)
            z_height: Cutting height in mm
            feed_rate: Feed rate in mm/min
            z_clearance: Safe clearance height in mm

        Returns:
            G-code as string
        """
        lines = []
        lines.append("; G-code generated from AI path detection")
        lines.append("; Generated by AI Welding Path Generator - IronSketch")
        lines.append(f"; Feed rate: {feed_rate:.1f} mm/min")
        lines.append(f"; Cut height: {z_height:.1f} mm")
        lines.append(f"; Clearance height: {z_clearance:.1f} mm")
        lines.append("")

        lines.append("G21 ; Set units to millimeters")
        lines.append("G90 ; Absolute positioning")
        lines.append("G17 ; XY plane selection")
        lines.append(f"G0 Z{z_clearance:.1f} ; Move to clearance height")
        lines.append("")

        for path_idx, path in enumerate(paths, 1):
            lines.append(f"; Path {path_idx}")

            if path:
                x_start, y_start = path[0]
                lines.append(f"G0 X{x_start:.3f} Y{y_start:.3f} ; Rapid to start")
                lines.append(f"G1 Z{z_height:.3f} F{feed_rate:.1f} ; Lower to cut height")
                lines.append("M3 ; Start plasma torch")

                for x_mm, y_mm in path[1:]:
                    lines.append(f"G1 X{x_mm:.3f} Y{y_mm:.3f} F{feed_rate:.1f}")

                lines.append("M5 ; Stop plasma torch")
                lines.append(f"G0 Z{z_clearance:.1f} ; Raise to clearance")
                lines.append("")

        lines.append("M30 ; End program")

        return "\n".join(lines)

    @staticmethod
    def map_speed_to_thickness(speed_mm_s: float, min_speed: float = 10.0, max_speed: float = 30.0) -> str:
        """
        Map speed to line thickness description.

        Args:
            speed_mm_s: Speed in mm/s
            min_speed: Minimum speed
            max_speed: Maximum speed

        Returns:
            Thickness description
        """
        normalized = (speed_mm_s - min_speed) / (max_speed - min_speed)

        if normalized <= 0.33:
            return "Thick lines (slow speed)"
        elif normalized <= 0.67:
            return "Medium lines (medium speed)"
        else:
            return "Thin lines (fast speed)"

    @staticmethod
    def generate_parameter_file(
        architecture: str,
        speed_mm_s: float,
        scale_mm_per_px: float,
        origin_x: float,
        origin_y: float,
        z_height: float,
        num_paths: int,
        num_points: int,
        simplify_epsilon: float,
        post_process_params: dict
    ) -> str:
        """
        Generate parameter documentation file.

        Args:
            architecture: Model architecture used
            speed_mm_s: Movement speed
            scale_mm_per_px: Coordinate scale
            origin_x: X origin offset
            origin_y: Y origin offset
            z_height: Z height
            num_paths: Number of paths
            num_points: Total points
            simplify_epsilon: Simplification parameter
            post_process_params: Post-processing parameters

        Returns:
            Parameter file content
        """
        lines = []
        lines.append("=" * 60)
        lines.append("AI WELDING PATH GENERATOR - IRONSKETCH - PROCESSING PARAMETERS")
        lines.append("=" * 60)
        lines.append("")

        lines.append("MODEL CONFIGURATION")
        lines.append("-" * 60)
        lines.append(f"Architecture: {architecture.upper()}")
        lines.append("")

        lines.append("ROBOT WORKSPACE MAPPING")
        lines.append("-" * 60)
        lines.append(f"Scale: {scale_mm_per_px} mm/pixel")
        lines.append(f"Origin X offset: {origin_x:.1f} mm")
        lines.append(f"Origin Y offset: {origin_y:.1f} mm")
        lines.append(f"Z height: {z_height:.1f} mm")
        lines.append(f"Speed: {speed_mm_s:.1f} mm/s")
        lines.append(f"Line type: {RobotScriptGenerator.map_speed_to_thickness(speed_mm_s)}")
        lines.append("")

        lines.append("VECTORIZATION SETTINGS")
        lines.append("-" * 60)
        lines.append(f"Simplification epsilon: {simplify_epsilon}")
        lines.append(f"Morphological closing kernel: {post_process_params.get('close_kernel', 3)}")
        lines.append(f"Minimum contour area: {post_process_params.get('min_area', 100)} pixels")
        lines.append("")

        lines.append("RESULTS")
        lines.append("-" * 60)
        lines.append(f"Total paths: {num_paths}")
        lines.append(f"Total points: {num_points}")
        lines.append(f"Average points per path: {num_points / num_paths if num_paths > 0 else 0:.1f}")
        lines.append("")

        lines.append("=" * 60)

        return "\n".join(lines)
